NAZWA_ARKUSZA = "Karta_Punktowa" 
ADRES_APLIKACJI = "https://sft-schiesszettel.streamlit.app/"
KOD_KLUBU = "SFT"
dystanse_lista = ["18m", "20m", "30m", "40m", "50m", "60m", "70m"]

T = {
    "PL": {
        "title": "🏹 Karta Punktowa",
        "menu_home": "Home",
        "menu_score": "Schießzettel",
        "menu_multi": "Mini-Turniej",
        "menu_stats": "Statystyki",
        "menu_calendar": "Kalendarz",
        "menu_settings": "Ustawienia",
        "home_welcome": "Witaj",
        "home_last_training": "Ostatni trening:",
        "home_record": "Twój rekord na",
        "home_no_data": "Nie masz jeszcze żadnych wyników. Czas na trening!",
        "upcoming_events": "🗓️ Twoje nadchodzące wyjazdy/treningi",
        "no_events": "Brak zaplanowanych wydarzeń.",
        "training": "Trening",
        "tournament": "Turniej",
        "event_name": "Nazwa turnieju:",
        "event_name_ph": "np. Mistrzostwa Klubu",
        "choose_dist": "🎯 **Wybierz dystans:**",
        "room_code": "2-cyfrowy kod pokoju (np. 12):",
        "start_btn": "🚀 ROZPOCZNIJ STRZELANIE",
        "start_multi_btn": "⚔️ DOŁĄCZ I ROZPOCZNIJ",
        "lang_label": "Wybierz język / Sprache:",
        "dist": "Dystans",
        "total_score": "Wynik Całkowity",
        "pts": "Punkty",
        "arrow_cnt": "Licznik",
        "eff": "Skuteczność",
        "warmup": "Rozgrzewka / Próbne",
        "add_6": "➕ 6",
        "add_1": "➕ 1",
        "undo": "➖ 1",
        "finish": "💾 Zapisz",
        "cancel_btn": "❌ Usuń",
        "pause_btn": "⏸️ Pauza",
        "resume_btn": "▶️ Kontynuuj",
        "discard_btn": "🗑️ Odrzuć",
        "unfinished_msg": "⚠️ Masz wstrzymany trening w tle!",
        "sum_10_x": "Suma 10+X:",
        "only_x": "Same X:",
        "round_fin": "✅ Runda 1 (Zakończona)",
        "bow_setup": "🏹 Łuk (Bogen-Setup)",
        "draw_weight": "Siła (Zuggewicht) [lbs]",
        "brace_height": "Wys. cięciwy (Standhöhe) [cm/in]",
        "tiller": "Tiller [mm]",
        "nock_point": "P. siodełka (Nockpunkt) [mm]",
        "arrows_setup": "🎯 Strzały (Pfeile)",
        "arr_model": "Model (Modell)",
        "arr_spine": "Sztywność (Spine)",
        "arr_len": "Długość (Länge) [in]",
        "arr_point": "Waga grotu (Spitze) [gr]",
        "visier": "🔭 Celownik (Visier)",
        "choose_dist_settings": "Zaznacz widoczne dystanse na torze:",
        "dl_equip_txt": "📥 Pobierz profil sprzętu",
        "dl_stats_csv": "📥 Pobierz statystyki (CSV)",
        "rank_title": "🏆 Tabela Wyników (Ważna 12 godzin!)",
        "rank_btn": "🔄 Odśwież tabelę",
        "rank_empty": "Brak wyników z ostatnich 12 godzin dla tego kodu. Bądź pierwszy!",
        "stat_no_data": "Brak danych dla tego dystansu. Idź postrzelać! 🏹",
        "stat_metric": "Pokaż na wykresie:",
        "my_plan": "Mój Terminarz",
        "my_diary": "Mój Dziennik",
        "add_event": "➕ Dodaj wydarzenie",
        "event_date": "Data",
        "event_event_name": "Nazwa wydarzenia",
        "event_address": "Adres (opcjonalnie)",
        "nav_btn": "Nawiguj"
    },
    "DE": {
        "title": "🏹 Schießzettel",
        "menu_home": "Home",
        "menu_score": "Schießzettel",
        "menu_multi": "Mini-Turnier",
        "menu_stats": "Statistiken",
        "menu_calendar": "Kalender",
        "menu_settings": "Einstellungen",
        "home_welcome": "Willkommen",
        "home_last_training": "Dein letztes Training:",
        "home_record": "Dein Rekord auf",
        "home_no_data": "Noch keine Ergebnisse vorhanden. Zeit für ein Training!",
        "upcoming_events": "🗓️ Deine nächsten Termine",
        "no_events": "Keine geplanten Ereignisse.",
        "training": "Training",
        "tournament": "Turnier",
        "event_name": "Turniername:",
        "event_name_ph": "z.B. Vereinsmeisterschaft",
        "choose_dist": "🎯 **Wähle Distanz:**",
        "room_code": "2-stelliger Raumcode (z.B. 12):",
        "start_btn": "🚀 SCHIESSEN STARTEN",
        "start_multi_btn": "⚔️ BEITRETEN & STARTEN",
        "lang_label": "Sprache / Wybierz język:",
        "dist": "Distanz",
        "total_score": "Gesamtergebnis",
        "pts": "Punkte",
        "arrow_cnt": "Pfeile",
        "eff": "Quote",
        "warmup": "Probepfeile",
        "add_6": "➕ 6",
        "add_1": "➕ 1",
        "undo": "➖ 1",
        "finish": "💾 Speichern",
        "cancel_btn": "❌ Löschen",
        "pause_btn": "⏸️ Pause",
        "resume_btn": "▶️ Fortsetzen",
        "discard_btn": "🗑️ Verwerfen",
        "unfinished_msg": "⚠️ Du hast ein pausiertes Training im Hintergrund!",
        "sum_10_x": "Summe 10+X:",
        "only_x": "Nur X:",
        "round_fin": "✅ Runde 1 (Beendet)",
        "bow_setup": "🏹 Bogen-Setup",
        "draw_weight": "Zuggewicht [lbs]",
        "brace_height": "Standhöhe [cm/in]",
        "tiller": "Tiller [mm]",
        "nock_point": "Nockpunkt [mm]",
        "arrows_setup": "🎯 Pfeile",
        "arr_model": "Modell",
        "arr_spine": "Spine-Wert",
        "arr_len": "Pfeillänge [in]",
        "arr_point": "Spitzengewicht [gr]",
        "visier": "🔭 Visier",
        "choose_dist_settings": "Sichtbare Distanzen markieren:",
        "dl_equip_txt": "📥 Ausrüstungsprofil herunterladen",
        "dl_stats_csv": "📥 Statistiken herunterladen (CSV)",
        "rank_title": "🏆 Live-Rangliste (12 Stunden gültig!)",
        "rank_btn": "🔄 Tabelle aktualisieren",
        "rank_empty": "Keine Ergebnisse aus den letzten 12 Stunden für diesen Code. Sei der Erste!",
        "stat_no_data": "Keine Daten für diese Distanz. Geh schießen! 🏹",
        "stat_metric": "Zeige im Diagramm:",
        "my_plan": "Mein Terminplan",
        "my_diary": "Mein Tagebuch",
        "add_event": "➕ Ereignis hinzufügen",
        "event_date": "Datum",
        "event_event_name": "Name des Ereignisses",
        "event_address": "Adresse (optional)",
        "nav_btn": "Route"
    }
}
